### ISSUE TITLE
Mettre en place le mock de datas

### ISSUE THREAD

**Issue by fodil-a** [TeamTajweed/tajweed-back#6]
Analyser les technos utilisable et une fois la meilleure approche trouvée, réaliser des POCs

Quelques pistes:
- [Mongobee + profiles](https://github.com/mongobee/mongobee#using-spring-profiles)
- mongodump et copie dans l'image docker (au moment du build)

**Comment by othAs-dev** [comment]
@martinez-guillaume do you done this task pls?

**Comment by martinez-guillaume** [comment]
Yes, I think it's good now. Wait for Fodil's approval

**Comment by fodil-a** [comment]
@martinez-guillaume I updated your PR with changes to do, here is the message:

Can you use the profiles, so that it's run only when we use a specific profile, like "dev"
You can do that by following [this](https://www.baeldung.com/spring-profiles)
You have to create the profile in pom.xml (see section 4.6) and basically just add `@Profile("dev")` in the class you created.

And if you want to do even better, try to have real names/information.
To do that, you have to use [this](https://github.com/DiUS/java-faker)

This is going to be fun !!

**Comment by fodil-a** [comment]
Done, you populate data by activating the profile 'populate'

Thanks @martinez-guillaume

**Comment by martinez-guillaume** [comment]
I just saw your message now. I will take care of it right away.

**Comment by fodil-a** [comment]
> I just saw your message now. I will take care of it right away.

Noo it works like that, no change needed !! 😋

**Comment by martinez-guillaume** [comment]
Cool , it's OK.
